### ISSUE TITLE
Need Sections For Each Below

### ISSUE THREAD

**Issue by tinayang15** [Lementknight/pe-portfolio-site#2]
- Photo of yourself
- About Section
- Previous Work Experiences
- Hobbies (images needed)
- current/previous education
- map of locations/countries visited

**Comment by Lementknight** [comment]
I believe that we can utilize [Jinja](https://jinja.palletsprojects.com/en/3.0.x/api/#basics) to create a template for each section of the site.

**Comment by Lementknight** [comment]
I believe that we can utilize [Jinja](https://jinja.palletsprojects.com/en/3.0.x/api/#basics) to create a template for each section of the site.

**Comment by tinayang15** [comment]
In the requirements, hobbies needs it's own page.

**Comment by Lementknight** [comment]
I dub this issue, reopened!

**Comment by tinayang15** [comment]
> In the requirements, hobbies needs it's own page.

I moved hobbies to it's own page and has it's own route.

**Comment by tinayang15** [comment]
Created a carousel to display hobbies on it's page.

2 Photos of Caleb was added was added to the home page.

Added about section for Caleb on Home page.

Previous work experience added under experience tab in a timeline.

**Comment by Lementknight** [comment]
I embedded Google Maps into the experiences site

I integrated Jinja components for redundant code, example of this being the head tag, the navbar, and the scripts tag
